# Generated by Django 4.2.11 on 2026-06-10 05:27

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_onboarding', '0002_employee_rejoined_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('institute', models.CharField(max_length=200)),
                ('course_at_institute', models.CharField(max_length=100)),
                ('student_type', models.CharField(choices=[('INTERN', 'Intern'), ('TRAINEE', 'Trainee'), ('PROJECT_STUDENT', 'Project Student'), ('INDUSTRIAL_VISIT', 'Industrial Visit')], max_length=30)),
                ('program_name', models.CharField(max_length=100)),
                ('mentor', models.CharField(blank=True, max_length=100, null=True)),
                ('joining_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('project_description', models.TextField(blank=True, null=True)),
                ('cert_type', models.CharField(choices=[('INTERNSHIP_CERT', 'Internship Certificate'), ('TRAINING_CERT', 'Training Completion Certificate'), ('PROJECT_CERT', 'Project Completion Certificate')], max_length=30)),
                ('cert_no', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DISCONTINUED', 'Discontinued')], default='ACTIVE', max_length=20)),
                ('cert_pdf', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('total_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_students', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='employee_onboarding.department')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeeInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid')], default='UNPAID', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='student_certificate.student')),
            ],
        ),
    ]
