# Generated by Django 4.2.11 on 2026-06-22

from django.db import migrations

def seed_courses_and_skills(apps, schema_editor):
    Course = apps.get_model('student_certificate', 'Course')
    
    courses_data = [
        {
            "course_name": "MERN Stack",
            "default_duration": "6 months",
            "skills_list": ["HTML5", "CSS3", "JavaScript", "MongoDB", "Express.js", "Reactjs", "NodeJs"]
        },
        {
            "course_name": "Python AI/ML",
            "default_duration": "6 months",
            "skills_list": ["Python", "ML", "Deep Learning", "Generative AI", "Django", "Flask", "Fast API"]
        },
        {
            "course_name": "Web designing",
            "default_duration": "6 months",
            "skills_list": ["HTML5", "CSS3", "Bootstrap", "Wordpress", "Photoshop"]
        },
        {
            "course_name": "Full Stack",
            "default_duration": "6 months",
            "skills_list": ["HTML5", "CSS3", "JavaScript", "ReactJS", "MongoDB", "NodeJS"]
        },
        {
            "course_name": "Graphic Designing",
            "default_duration": "6 months",
            "skills_list": ["Photoshop", "Illustrator", "Figma", "Canva"]
        },
        {
            "course_name": "Frontend (React JS)",
            "default_duration": "6 months",
            "skills_list": ["HTML5", "CSS3", "JavaScript", "ReactJS", "Bootstrap", "Tailwind CSS"]
        },
        {
            "course_name": "PHP",
            "default_duration": "6 months",
            "skills_list": ["Laravel", "Core PHP", "Wordpress", "Shopify"]
        }
    ]
    
    # 1. Delete all other courses (previous/old courses)
    allowed_names = [c["course_name"] for c in courses_data]
    Course.objects.exclude(course_name__in=allowed_names).delete()
    
    # 2. Add or update the 7 courses
    for c in courses_data:
        Course.objects.update_or_create(
            course_name=c["course_name"],
            defaults={
                "default_duration": c["default_duration"],
                "skills_list": c["skills_list"]
            }
        )

def remove_seeded_courses(apps, schema_editor):
    Course = apps.get_model('student_certificate', 'Course')
    names = [
        "MERN Stack", "Python AI/ML", "Web designing", "Full Stack",
        "Graphic Designing", "Frontend (React JS)", "PHP"
    ]
    Course.objects.filter(course_name__in=names).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('student_certificate', '0002_course_student_address_student_father_name_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_courses_and_skills, remove_seeded_courses),
    ]
