# Generated by Django 4.2.11 on 2026-06-22 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student_certificate.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_certificate', '0003_seed_courses_and_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(upload_to=student_certificate.models.student_upload_to_uuid_filename)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='student_certificate.student')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_student_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
