# Generated by Django 4.2.11 on 2026-06-24 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_certificate', '0004_studentdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcertificate',
            name='calculated_completed_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcertificate',
            name='early_generation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcertificate',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_certificates', to=settings.AUTH_USER_MODEL),
        ),
    ]
