# Generated by Django 4.2.11 on 2026-06-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_certificate', '0005_studentcertificate_calculated_completed_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='selected_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentcertificate',
            name='display_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
