"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 5.2.15.
For more information, see https://docs.djangoproject.com/en/5.2/topics/settings/
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env', override=True)

# Add 'apps' folder to Python path (so custom apps can be imported without 'apps.')
sys.path.insert(0, str(BASE_DIR / 'apps'))

# Configure DLL path for WeasyPrint/GTK on Windows
tess_path = r"C:\Program Files\Tesseract-OCR"
if os.path.exists(tess_path):
    os.environ["PATH"] = tess_path + os.pathsep + os.environ.get("PATH", "")
    if hasattr(os, "add_dll_directory"):
        try:
            os.add_dll_directory(tess_path)
        except Exception:
            pass


# ---------- SECURITY ----------
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-$$exa==o9et_2o5x5x&nuqgepp!hr0sxh%9-4iu6(rkn0qmvvh')
DEBUG = os.getenv('DEBUG', 'True') == 'True'
ALLOWED_HOSTS = os.getenv(
    'ALLOWED_HOSTS',
    'localhost,127.0.0.1,overmournfully-overnervous-narcisa.ngrok-free.dev'
).split(',')
if DEBUG:
    ALLOWED_HOSTS.extend(['.ngrok-free.app', '.ngrok-free.dev', '.ngrok.dev'])

# ---------- APPLICATION DEFINITION ----------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',   # kept because Django admin needs it, but API will not use session auth
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',   # <-- add this
    'corsheaders',
    'django_filters',
    'import_export',

    # Custom apps
    'accounts',
    'roles',
    'employee_onboarding',
    'salary',
    'exit_formality',
    'student_certificate',
    'notifications',
    'audit_logs',
    'common',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS must be high
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'common.middleware.CurrentUserMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],   # global templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# ---------- DATABASE (PostgreSQL) ----------
import sys
if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'hr_portal'),
            'USER': os.getenv('DB_USER', 'hr_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }

# ---------- PASSWORD VALIDATION ----------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ---------- INTERNATIONALIZATION (INDIAN TIME ZONE) ----------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'      # Indian time zone (IST)
USE_I18N = True
USE_TZ = True

X_FRAME_OPTIONS = 'SAMEORIGIN'

# ---------- STATIC & MEDIA FILES ----------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ---------- DEFAULT PRIMARY KEY ----------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.User'

# ---------- DJANGO REST FRAMEWORK (DRF) ----------

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',   # no browsable API
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# ---------- CORS (if frontend is separate) ----------
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000').split(',')
CORS_ALLOW_CREDENTIALS = True

# ---------- EMAIL (for exit workflow) ----------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# If email credentials are missing, use console backend for development
if not EMAIL_HOST_USER:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# ---------- AUTHENTICATION BACKENDS ----------
AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailOrUsernameModelBackend',
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ---------- CELERY SETTINGS ----------
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'daily-onboarding-graduation-and-alerts': {
        'task': 'notifications.tasks.run_daily_onboarding_pipeline',
        'schedule': crontab(hour=8, minute=0),  # Daily at 08:00 IST
    },
    'daily-bitrix-sync-retry': {
        'task': 'notifications.tasks.retry_failed_bitrix_syncs',
        'schedule': crontab(hour=9, minute=0),  # Daily at 09:00 IST
    },
}

# ---------- COMPANY & SIGNATORY DEFAULTS FOR LETTERS ----------
COMPANY_NAME = "Devex Hub Pvt Ltd."
COMPANY_ADDRESS = "Plot No D-254, Fourth Floor, Phase 8A, Industrial Area, Mohali"
LETTER_SIGNATORY_NAME = os.getenv('LETTER_SIGNATORY_NAME', 'Head of HR Operations')
LETTER_SIGNATORY_DESIGNATION = os.getenv('LETTER_SIGNATORY_DESIGNATION', 'Authorized Signatory')

