# Generated by Django 4.2.11 on 2026-06-10 05:26

import apps.common.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_onboarding', '0002_employee_rejoined_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('basic', apps.common.fields.EncryptedDecimalField(default=Decimal('0.00'), max_length=255)),
                ('hra', apps.common.fields.EncryptedDecimalField(default=Decimal('0.00'), max_length=255)),
                ('conveyance', apps.common.fields.EncryptedDecimalField(default=Decimal('0.00'), max_length=255)),
                ('medical', apps.common.fields.EncryptedDecimalField(default=Decimal('0.00'), max_length=255)),
                ('special', apps.common.fields.EncryptedDecimalField(default=Decimal('0.00'), max_length=255)),
                ('monthly_bonus', apps.common.fields.EncryptedDecimalField(default=Decimal('0.00'), max_length=255)),
                ('other_allowances', models.JSONField(blank=True, default=list)),
                ('pf', apps.common.fields.EncryptedDecimalField(default=Decimal('0.00'), max_length=255)),
                ('professional_tax', apps.common.fields.EncryptedDecimalField(default=Decimal('200.00'), max_length=255)),
                ('tds', apps.common.fields.EncryptedDecimalField(default=Decimal('0.00'), max_length=255)),
                ('other_deductions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salaries', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='employee_onboarding.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payslip_no', models.CharField(max_length=30, unique=True)),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('working_days', models.PositiveIntegerField()),
                ('days_worked', models.PositiveIntegerField()),
                ('lop_days', models.PositiveIntegerField(default=0)),
                ('one_time_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('one_time_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash')], default='BANK_TRANSFER', max_length=20)),
                ('pdf_file', models.FileField(upload_to='salary_slips/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_slips', to='employee_onboarding.employee')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_slips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryIncrementReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anniversary_date', models.DateField()),
                ('reminder_15_sent', models.BooleanField(default=False)),
                ('reminder_7_sent', models.BooleanField(default=False)),
                ('reminder_0_sent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Actioned', 'Actioned')], default='Pending', max_length=20)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('actioned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actioned_reminders', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='increment_reminders', to='employee_onboarding.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryIncrementApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_basic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_hra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_allowances', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('increment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('increment_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField()),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(upload_to='salary_increments/')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_increments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='increment_approvals', to='employee_onboarding.employee')),
                ('reminder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='salary.salaryincrementreminder')),
            ],
        ),
    ]
