# Generated by Django 4.2.11 on 2026-06-10 06:40

import common.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarystructure',
            name='basic',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00'), max_length=255),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='conveyance',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00'), max_length=255),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='hra',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00'), max_length=255),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='medical',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00'), max_length=255),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='monthly_bonus',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00'), max_length=255),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='pf',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00'), max_length=255),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='professional_tax',
            field=common.fields.EncryptedDecimalField(default=Decimal('200.00'), max_length=255),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='special',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00'), max_length=255),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='tds',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00'), max_length=255),
        ),
    ]
