# Generated by Django 4.2.11 on 2026-06-15 05:55

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_onboarding', '0006_employee_bank_account_employee_pan_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salary', '0002_alter_salarystructure_basic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarystructure',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='monthly_bonus',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='other_allowances',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='other_deductions',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='pf',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='professional_tax',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='special',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='tds',
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='basic',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='conveyance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='esi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='loan_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='medical',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='net_credited_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='other_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='payable_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='pf_employee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='professional_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='special_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='tds',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='pf_employer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='special_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='payslip_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='salary_slips/'),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='basic',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='conveyance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='medical',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='salaryslip',
            unique_together={('employee', 'month', 'year')},
        ),
        migrations.CreateModel(
            name='SalaryImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('total_records', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('processing', 'Processing')], default='processing', max_length=20)),
                ('error_report_path', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='days_worked',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='generated_at',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='gross',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='net_pay',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='one_time_bonus',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='one_time_deduction',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='working_days',
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='uploaded_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slips', to='salary.salaryimportbatch'),
        ),
    ]
