# Generated by Django 4.2.11 on 2026-06-15 11:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_remove_salarystructure_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryslip',
            name='basic',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='conveyance',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='hra',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='loan_deduction',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='lop_days',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='medical',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='other_earnings',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='payable_days',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='pf_employee',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='special_allowance',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='tds',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='basic',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='conveyance',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='hra',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='medical',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='pf_employer',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='special_allowance',
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='extra_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='labour_welfare_fund',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='leaves_available',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='location',
            field=models.CharField(default='Mohali', max_length=100),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='pf_contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='working_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='esi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='labour_welfare_fund',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='pf_contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='professional_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
