# Generated by Django 4.2.11 on 2026-06-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_remove_salaryslip_basic_remove_salaryslip_bonus_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salaryslip',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='salaryincrementapproval',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='salaryincrementreminder',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='employee',
        ),
        migrations.AddField(
            model_name='salaryincrementapproval',
            name='bitrix_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salaryincrementreminder',
            name='bitrix_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='bitrix_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='bitrix_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='salaryslip',
            unique_together={('bitrix_user_id', 'month', 'year')},
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='employee',
        ),
    ]
