# Generated by Django 4.2.11 on 2026-06-16 07:25

import common.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_remove_salaryslip_basic_remove_salaryslip_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryincrementapproval',
            name='increment_amount',
            field=common.fields.EncryptedDecimalField(),
        ),
        migrations.AlterField(
            model_name='salaryincrementapproval',
            name='increment_pct',
            field=common.fields.EncryptedDecimalField(),
        ),
        migrations.AlterField(
            model_name='salaryincrementapproval',
            name='new_allowances',
            field=common.fields.EncryptedDecimalField(),
        ),
        migrations.AlterField(
            model_name='salaryincrementapproval',
            name='new_basic',
            field=common.fields.EncryptedDecimalField(),
        ),
        migrations.AlterField(
            model_name='salaryincrementapproval',
            name='new_hra',
            field=common.fields.EncryptedDecimalField(),
        ),
        migrations.AlterField(
            model_name='salaryincrementapproval',
            name='new_net',
            field=common.fields.EncryptedDecimalField(),
        ),
        migrations.AlterField(
            model_name='salaryincrementapproval',
            name='old_net',
            field=common.fields.EncryptedDecimalField(),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='esi',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='gross_salary',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='labour_welfare_fund',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='net_credited_amount',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='net_salary',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='other_deductions',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='pf_contribution',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='professional_tax',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='total_deductions',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='esi',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='gross_salary',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='labour_welfare_fund',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='other_deductions',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='pf_contribution',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='professional_tax',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
    ]
