# Generated by Django 4.2.11 on 2026-06-17 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0005_alter_salaryincrementapproval_increment_amount_and_more'),
        ('salary', '0005_alter_salaryslip_unique_together_and_more'),
    ]

    operations = [
    ]
