# Generated by Django 4.2.11 on 2026-06-17 06:22

import common.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0006_merge_20260617_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryslip',
            name='esi',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='extra_days',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='gross_salary',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='labour_welfare_fund',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='leaves_available',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='net_credited_amount',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='net_salary',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='other_deductions',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='pf_contribution',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='professional_tax',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='total_deductions',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='working_days',
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='bank_account_no',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='cl',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='extra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='extra_days_working',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='fine_advance',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='month_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='month_salary',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='net_payable',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='payable_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='payable_salary',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='weekend',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='worked_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
