# Generated by Django 4.2.11 on 2026-06-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0007_remove_salaryslip_esi_remove_salaryslip_extra_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_user_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('bank_account_no', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
