# Generated by Django 4.2.11 on 2026-06-25 10:25

import common.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0008_employeebankdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarystructure',
            name='basic_salary',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='conveyance',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='ctc',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='esi_employee',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='esi_employer',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='hra',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='in_hand_salary',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='lwf',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='medical_allowance',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='monthly_bonus',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='pf_employee',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='pf_employer',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='special_allowance',
            field=common.fields.EncryptedDecimalField(default=Decimal('0.00')),
        ),
    ]
