# Generated by Django 4.2.11 on 2026-07-03 06:16

import common.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salary', '0009_salarystructure_basic_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DismissedEmployeeBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_user_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('bank_account_no', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DismissedSalaryImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('total_records', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('processing', 'Processing')], default='processing', max_length=20)),
                ('error_report_path', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_salary_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DismissedSalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_user_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('gross_salary', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
                ('pf_contribution', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
                ('esi', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
                ('labour_welfare_fund', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
                ('professional_tax', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
                ('other_deductions', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
                ('effective_from', models.DateField()),
                ('ctc', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
                ('basic_salary', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
                ('hra', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
                ('conveyance', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
                ('medical_allowance', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
                ('special_allowance', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
                ('monthly_bonus', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
                ('esi_employer', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
                ('pf_employer', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
                ('pf_employee', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
                ('esi_employee', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
                ('lwf', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
                ('in_hand_salary', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
            ],
        ),
        migrations.CreateModel(
            name='DismissedSalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_user_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('location', models.CharField(default='Mohali', max_length=100)),
                ('month_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('worked_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('weekend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('cl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('extra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('payable_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('month_salary', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
                ('payable_salary', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
                ('extra_days_working', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
                ('fine_advance', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
                ('net_payable', common.fields.EncryptedDecimalField(default=Decimal('0.00'))),
                ('bank_account_no', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('transaction_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('payslip_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='dismissed_salary_slips/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uploaded_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slips', to='salary.dismissedsalaryimportbatch')),
            ],
            options={
                'unique_together': {('bitrix_user_id', 'month', 'year')},
            },
        ),
    ]
