# Generated by Django 4.2.11 on 2026-06-10 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rejoined_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenures', to='employee_onboarding.employee'),
        ),
    ]
