# Generated by Django 4.2.11 on 2026-06-10 06:40

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_onboarding', '0002_employee_rejoined_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadhaar_encrypted',
            field=common.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pan_encrypted',
            field=common.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
