# Generated by Django 4.2.11 on 2026-06-11 11:52

from django.db import migrations, models
import employee_onboarding.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_onboarding', '0003_alter_employee_aadhaar_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bitrix_contact_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bitrix_sync_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bitrix_sync_status',
            field=models.CharField(choices=[('Synced', 'Synced'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='onboarding_complete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='doc_type',
            field=models.CharField(choices=[('RESUME', 'Resume / CV'), ('AADHAAR', 'Aadhaar Card (scan/photo)'), ('PAN', 'PAN Card (scan/photo)'), ('OFFER_LETTER', 'Offer Letter (signed copy)'), ('APPOINTMENT_LETTER', 'Appointment Letter (signed copy)'), ('BOND_LETTER', 'Bond / Service Agreement (signed copy)'), ('EDU_CERT', 'Educational Certificates'), ('EXP_LETTER', 'Previous Experience Letter'), ('BANK_DETAILS', 'Bank Account Details / Cancelled Cheque'), ('OTHER', 'Other (custom label)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(upload_to=employee_onboarding.models.upload_to_uuid_filename),
        ),
    ]
