# Generated by Django 4.2.11 on 2026-06-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_onboarding', '0004_employee_bitrix_contact_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('OFFER_LETTER', 'Offer Letter'), ('APPOINTMENT_LETTER', 'Appointment Letter'), ('BOND_LETTER', 'Bond Letter')], max_length=30, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('html_content', models.TextField()),
                ('allow_hr_edit', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
