# Generated by Django 4.2.11 on 2026-06-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_onboarding', '0005_lettertemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='doc_type',
            field=models.CharField(choices=[('RESUME', 'Resume / CV'), ('AADHAAR', 'Aadhaar Card (scan/photo)'), ('PAN', 'PAN Card (scan/photo)'), ('OFFER_LETTER', 'Offer Letter (signed copy)'), ('APPOINTMENT_LETTER', 'Appointment Letter (signed copy)'), ('BOND_LETTER', 'Bond / Service Agreement (signed copy)'), ('EDU_CERT', 'Educational Certificates'), ('EXP_LETTER', 'Previous Experience Letter'), ('BANK_DETAILS', 'Bank Account Details / Cancelled Cheque'), ('RELIEVING_LETTER', 'Relieving Letter'), ('EXPERIENCE_LETTER', 'Experience Letter'), ('NOTICE_LETTER', 'Notice Period Letter'), ('NOC_LETTER', 'No-Objection Certificate'), ('FF_SETTLEMENT_LETTER', 'Full & Final Settlement Letter'), ('FF_SALARY_SLIP', 'Final Month Salary Slip'), ('OTHER', 'Other (custom label)')], max_length=30),
        ),
    ]
