# Generated by Django 4.2.11 on 2026-06-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_onboarding', '0005_lettertemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pan_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
