# Generated by Django 4.2.11 on 2026-06-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_onboarding', '0006_alter_employeedocument_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
