# Generated by Django 4.2.11 on 2026-06-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_onboarding', '0007_employee_exit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettertemplate',
            name='name',
            field=models.CharField(choices=[('OFFER_LETTER', 'Offer Letter'), ('APPOINTMENT_LETTER', 'Appointment Letter'), ('BOND_LETTER', 'Bond Letter'), ('RELIEVING_LETTER', 'Relieving Letter'), ('EXPERIENCE_LETTER', 'Experience Letter'), ('NOTICE_LETTER', 'Notice Period Letter'), ('NOC_LETTER', 'NOC Letter'), ('FF_SETTLEMENT_LETTER', 'F&F Settlement Letter'), ('FF_SALARY_SLIP', 'Final Month Payslip')], max_length=30, unique=True),
        ),
    ]
