# Generated by Django 4.2.11 on 2026-06-16 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_onboarding', '0006_employee_bank_account_employee_pan_no'),
        ('employee_onboarding', '0008_alter_lettertemplate_name'),
    ]

    operations = [
    ]
