# Generated by Django 4.2.11 on 2026-06-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0005_alter_salaryslip_unique_together_and_more'),
        ('exit_formality', '0005_remove_exitrequest_employee_and_more'),
        ('employee_onboarding', '0009_merge_20260616_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedocument',
            name='employee',
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='bitrix_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
