# Generated by Django 4.2.11 on 2026-06-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_onboarding', '0011_syncedemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncedemployee',
            name='bitrix_sync_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncedemployee',
            name='bitrix_sync_status',
            field=models.CharField(choices=[('Synced', 'Synced'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
