# Generated by Django 4.2.11 on 2026-06-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_onboarding', '0012_syncedemployee_bitrix_sync_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncedemployee',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
