# Generated by Django 4.2.11 on 2026-06-10 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_onboarding', '0002_employee_rejoined_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resignation_date', models.DateField()),
                ('last_working_day', models.DateField()),
                ('exit_type', models.CharField(choices=[('RESIGNATION', 'Resignation'), ('TERMINATION', 'Termination'), ('RETIREMENT', 'Retirement'), ('CONTRACT_END', 'Contract End'), ('ABSCONDING', 'Absconding')], max_length=20)),
                ('exit_reason', models.TextField()),
                ('notice_waiver', models.BooleanField(default=False)),
                ('notice_letter_required', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_requests', to='employee_onboarding.employee')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_exits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExitSecureLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('exit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_links', to='exit_formality.exitrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ExitFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_laptop_returned', models.BooleanField(default=False)),
                ('asset_laptop_remarks', models.TextField(blank=True, null=True)),
                ('asset_id_returned', models.BooleanField(default=False)),
                ('asset_id_remarks', models.TextField(blank=True, null=True)),
                ('asset_access_card_returned', models.BooleanField(default=False)),
                ('asset_access_card_remarks', models.TextField(blank=True, null=True)),
                ('asset_others_details', models.TextField(blank=True, null=True)),
                ('kt_status', models.CharField(choices=[('COMPLETED', 'Completed'), ('IN_PROGRESS', 'In Progress'), ('NA', 'Not Applicable')], max_length=20)),
                ('kt_handover_to', models.CharField(blank=True, max_length=100, null=True)),
                ('kt_remarks', models.TextField(blank=True, null=True)),
                ('reason_dropdown', models.CharField(max_length=100)),
                ('reason_details', models.TextField(blank=True, null=True)),
                ('rating_env', models.PositiveIntegerField()),
                ('rating_mgmt', models.PositiveIntegerField()),
                ('recommend', models.CharField(max_length=10)),
                ('personal_email', models.EmailField(max_length=254)),
                ('personal_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exit_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_response', to='exit_formality.exitrequest')),
            ],
        ),
    ]
