# Generated by Django 4.2.11 on 2026-06-15 05:48

import common.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_onboarding', '0005_lettertemplate'),
        ('exit_formality', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exitrequest',
            old_name='notice_waiver',
            new_name='notice_period_waiver',
        ),
        migrations.RemoveField(
            model_name='exitformresponse',
            name='feedback',
        ),
        migrations.AddField(
            model_name='exitformresponse',
            name='asset_laptop_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exitformresponse',
            name='asset_locker_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitformresponse',
            name='asset_locker_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitformresponse',
            name='asset_mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exitformresponse',
            name='asset_mobile_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitformresponse',
            name='asset_mobile_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitformresponse',
            name='assets_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitformresponse',
            name='declaration_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitformresponse',
            name='improved_most',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitformresponse',
            name='kt_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitformresponse',
            name='kt_manager_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitformresponse',
            name='liked_most',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitformresponse',
            name='other_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitformresponse',
            name='personal_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitformresponse',
            name='rating_balance',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='cancelled_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='clearance_admin',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared'), ('NA', 'Not Applicable')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='clearance_finance',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared'), ('NA', 'Not Applicable')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='clearance_it',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared'), ('NA', 'Not Applicable')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='clearance_library',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared'), ('NA', 'Not Applicable')], default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='clearance_manager',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared'), ('NA', 'Not Applicable')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='it_biometric_deactivated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='it_data_backup_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='it_email_deactivated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='it_system_access_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='it_vpn_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='leave_balance_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='leave_policy_option',
            field=models.CharField(choices=[('ENCASHMENT', 'Encashment'), ('ADJUST', 'Adjust'), ('LAPSE', 'Lapse')], default='LAPSE', max_length=20),
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='mode_of_resignation',
            field=models.CharField(default='EMAIL', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_exits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='override_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='secure_link_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='secure_link_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exitsecurelink',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitsecurelink',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exitrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exit_requests', to='employee_onboarding.employee'),
        ),
        migrations.AlterField(
            model_name='exitrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERRIDDEN', 'Overridden'), ('CLEARANCES_DONE', 'Clearances Done'), ('FF_PROCESSED', 'F&F Processed'), ('FULLY_EXITED', 'Fully Exited'), ('CANCELLED', 'Cancelled'), ('REOPENED', 'Reopened')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='exitsecurelink',
            name='exit_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secure_link', to='exit_formality.exitrequest'),
        ),
        migrations.CreateModel(
            name='ExitFFSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_month_days', models.IntegerField(default=30)),
                ('salary_worked_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('salary_proportional', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('leave_encashment_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('leave_encashment_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leave_encashment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reimbursements_json', models.JSONField(blank=True, default=list)),
                ('bonus_arrears', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gratuity_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notice_shortfall_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notice_shortfall_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notice_shortfall_amount', common.fields.EncryptedDecimalField(default=Decimal('0.00'), max_length=255)),
                ('salary_advance_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bond_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions_json', models.JSONField(blank=True, default=list)),
                ('tds_deduction', common.fields.EncryptedDecimalField(default=Decimal('0.00'), max_length=255)),
                ('per_day_salary', common.fields.EncryptedDecimalField(default=Decimal('0.00'), max_length=255)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque')], default='BANK_TRANSFER', max_length=20)),
                ('expected_payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('employee_acknowledgement', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ff_settlements', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ff_settlements', to=settings.AUTH_USER_MODEL)),
                ('exit_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ff_settlement', to='exit_formality.exitrequest')),
                ('payment_processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_ff_settlements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
