# Generated by Django 4.2.11 on 2026-06-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exit_formality', '0002_rename_notice_waiver_exitrequest_notice_period_waiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitrequest',
            name='send_email_on_exit',
            field=models.BooleanField(default=True),
        ),
    ]
