# Generated by Django 4.2.11 on 2026-06-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exit_formality', '0003_exitrequest_send_email_on_exit'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitrequest',
            name='email_documents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
