# Generated by Django 4.2.11 on 2026-06-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exit_formality', '0004_exitrequest_email_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exitrequest',
            name='employee',
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='bitrix_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
